kind: pipeline
name: amd64
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ghcr.io/ow-api/balancer
      registry: ghcr.io
      tags:
        - latest